// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MidTerm.Data;

#nullable disable

namespace MidTerm.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240514033010_AddPatient&VeterinarianTable")]
    partial class AddPatientVeterinarianTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MidTerm.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalHistory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medications")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 4,
                            Breed = "Labrador Retriever",
                            ImageUrl = "None",
                            MedicalHistory = "None",
                            Medications = "Heartworm prevention",
                            Name = "Bella",
                            Species = "Dog"
                        },
                        new
                        {
                            Id = 2,
                            Age = 3,
                            Breed = "Siamese",
                            ImageUrl = "None",
                            MedicalHistory = "UTI Last Year",
                            Medications = "Flea prevention",
                            Name = "Max",
                            Species = "Cat"
                        },
                        new
                        {
                            Id = 3,
                            Age = 5,
                            Breed = "Beagle",
                            ImageUrl = "None",
                            MedicalHistory = "Minor hip dysplasia",
                            Medications = "Joint supplements",
                            Name = "Daisy",
                            Species = "Dog"
                        },
                        new
                        {
                            Id = 4,
                            Age = 2,
                            Breed = "Maine Coon",
                            ImageUrl = "None",
                            MedicalHistory = "Allergies",
                            Medications = "None",
                            Name = "Oliver",
                            Species = "Cat"
                        },
                        new
                        {
                            Id = 5,
                            Age = 6,
                            Breed = "German Shepherd",
                            ImageUrl = "None",
                            MedicalHistory = "Arthritis",
                            Medications = "Anti-inflammatory medication",
                            Name = "Charlie",
                            Species = "Dog"
                        });
                });

            modelBuilder.Entity("MidTerm.Models.Veterinarian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Veterinarians");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Dr. Sarah Johnson specializes in small animal surgery and has a passion for helping pets recover from injuries. She graduated from the University of California, Davis, and has been working in a busy urban clinic for over a decade. Dr. Johnson is known for her gentle approach and dedication to animal welfare.",
                            ImageUrl = "None",
                            Name = "Dr. Sarah Johnson",
                            YearsOfExperience = 12
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Dr. Michael Lee is an expert in veterinary cardiology and internal medicine. After completing his veterinary degree at Cornell University, he pursued further training in cardiac care for animals. Dr. Lee works at a renowned veterinary hospital and is committed to advancing heart health in pets through innovative treatments and research.",
                            ImageUrl = "None",
                            Name = "Dr. Michael Lee",
                            YearsOfExperience = 8
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Dr. Emily Rodriguez has a wealth of experience in exotic animal care, having worked with a variety of species including reptiles, birds, and small mammals. She earned her degree from the University of Florida and has since dedicated her career to the care and conservation of exotic animals. Dr. Rodriguez frequently volunteers at wildlife rescue centers and is a respected voice in the field of exotic animal medicine.",
                            ImageUrl = "None",
                            Name = "Dr. Emily Rodriguez",
                            YearsOfExperience = 15
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
